### ISSUE TITLE
Looks like ruby.rubocop does not work.

### ISSUE THREAD

**Issue by WIttyJudge** [mhartington/formatter.nvim#153]
I see builtin rubocop method is different compared to mine.

That is how my rubocop method looks and personally, it works:
```
local function rubocop()
  return {
    exe = 'rubocop', -- might prepend `bundle exec `
    args = {
      '--auto-correct', '--stdin', '%:p', '2>/dev/null', '|',
      "awk 'f; /^====================$/{f=1}'"
    },
    stdin = true
  }
end
```

It stopped working when I switched to builtin method.
```
    ruby = { 
      require('formatter.filetypes.ruby').rubocop,
    },
``

**Comment by mhartington** [comment]
Hmm, the `transform` _should_ be replacing the need for passing the output to `awk`. Got a sample ruby file I could test with?

**Comment by Hrle97** [comment]
@WIttyJudge I made that builtin and it worked for me for a time when I was writing in `ruby`. Like @mhartington said you could either provide a sample that it doesn't work with or try to fix it on your own.

You can try getting it to work with the `transform` parameter. Use the builtin in lua/formatter/filetypes/ruby.lua as a starting point like so:
```lua
function()
  return {
    exe = "rubocop",
    args = {
      "--fix-layout",
      "--stdin",
      util.escape_path(util.get_current_buffer_file_name()),
      "--format",
      "files",
    },
    stdin = true,
    transform = function(text)
      table.remove(text, 1)
      table.remove(text, 1)
      return text
    end,
  }
end
```
and try to get it working. If you find the solution please open a PR with the solution or just post it here and I'll open it.

**Comment by WIttyJudge** [comment]
To test it is so trivial. 
Open your terminal, type ``bundle init`` in a folder, than create file *.rb. 
When I tested it this way I described above, 
It worked but it had a different formatting. Have no idea why, check out your method and my method and maybe you will see it. Also, when I have tested your method in the 3 different rails project, it's totally not worked, just nothing happened after :FormatWrite.

**Comment by Hrle97** [comment]
You will have to excuse me because I was writing in `ruby` for less than a week in total because I had to fix a script for work, so I wrote this formatter config more to test the `transform` parameter and that is why I haven't properly tested it.

That said, you seem like you're well versed in `ruby`/`rubocop`, so can you help me a bit on this? As it turns out, `rubocop` is more than a formatter and getting it to work like a conventional formatter took a bit more work than I expected. The hardest part was getting to find the right command for the job, and I settled on this:

```
rubocop --fix-layout --stdin <file_path> --format files
```

, hence why the config is the way it is. Now, when you pipe your file to that like so:

```
cat <file_path> | rubocop --fix-layout --stdin <file_path> --format files
```

you will get something like this:

```
/opt/src/hrle/repos/ruby_format_test/test.rb
====================
puts 'Hello world!'
```

as a result. This is why `transform` is needed, to remove those first two lines that `rubocop` outputs (the file name and the equals signs), and this is exactly how `formatter.nvim` formats your `ruby` files with `rubocop`. Now, the help I would like from you is to test this on the command line with various files and try to get it to work the way you want to with different parameters. I can only help so much with the knowledge I have of ruby and maybe there are some limitation of `rubocop` that I am unaware of but that you will be able to spot.

Also, can you give me a link to a rails project that I can test the formatting in and some examples (a file that is properly formatted)? I have to know what it ought to look like in order to fix it.

**Comment by Hrle97** [comment]
Also, @mhartington, sometimes certain formatters require a prefix to the exe like `bundle exec` for `rubocop`. Do you suggest we just leave the `exe` this way, or add an argument for `bundle exec`?

I was thinking something like `env` for the parameter name, because, like in this example, you may not have `rubocop` in your path but you might have `bundle` in your path, and you could also prepend it with stuff like `GEM_PATH=vendor/gem`, so that `bundle` knows where to look for `rubocop`.
This could also be a solution for `node_modules` formatters like `prettier`. You could add something like `yarn` to the `env` parameter and then, rather than `prettier` being pulled from the `PATH`, `yarn` would do the resolution of either the local `prettier` installation or the global `prettier` installation.

**Comment by WIttyJudge** [comment]
@Hrle97 I have not idea what this command I shared actually do.
I've just copied one from this project https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/ruby.vim
If there is not rubocop.yml file inside rails or ruby project, it will work with the defaults settings.
If we have rubycop.yml, it will read that config.
In both cases, it works pretty and correct.

**Comment by gstokkink** [comment]
@Hrle97 the problem with the default transform function is that the filename is sometimes not echoed by rubocop, for instance when there is a syntax error (e.g., a missing `end`). In that case the transform function deletes a line too many. It's better to search for the occurrence of `====================` and use the content coming after, like the `awk` call does.

**Comment by cseelus** [comment]
Had to resort to `awk` too to use `autocorrect`:

```lua
ruby = {
  function()
    return {
      exe = "rubocop",
      args = {
        "--autocorrect",
        "--stdin",
        util.escape_path(util.get_current_buffer_file_name()),
        "--format files",
        "| awk 'f; /^====================$/{f=1}'",
      },
      stdin = true,
    }
  end
},
```

**Comment by Hrle97** [comment]
heya sry for the wait

will try to add the `===============` detection to the rubocop config today after work

**Comment by gstokkink** [comment]
> heya sry for the wait
> 
> 
> 
> will try to add the `===============` detection to the rubocop config today after work

Thanks! 🙏
