### ISSUE TITLE
Consider supporting Tidy for XML and XHTML

### ISSUE THREAD

**Issue by Diablo-D3** [mhartington/formatter.nvim#194]
Relevant Neoformat configs:
https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/xhtml.vim
https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/xml.vim
vs 
https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/html.vim

The only change seems to be `-asxhtml` and `-xml` respectively to the existing Tidy args.

**Comment by mhartington** [comment]
Pull requests are welcomed! I personally avoid xml and I dont recall the last time I've seen an xhtml doc. So I'm not an expert on what those will require. But if you're up for adding that as a default formatter, I'd accept a PR for it.

Otherwise, formatter.nvim supports having tools that are not part of the default setup.
