### ISSUE TITLE
Buffer is saved twice

### ISSUE THREAD

**Issue by zlksnk** [mhartington/formatter.nvim#42]
Follow up of #17 

**Reproduce**

<details><summary>Minimal repro config</summary>

```lua
local prettier = function()
	return {
		-- install from npm -> @fsouza/prettierd
		exe = "prettierd",
		args = {vim.api.nvim_buf_get_name(0)},
		stdin = true
	}
end

require('formatter').setup({
	logging = false,
	filetype = {
		typescript = { prettier },
		javascript = { prettier },
	}
})

vim.api.nvim_exec([[
augroup FormatAutogroup
	autocmd!
	autocmd BufWritePost *.ts,*.js FormatWrite
augroup END
]], true)
```
</details>

Steps to reproduce:
- Install `@fsouza/prettierd` from  `npm`
- Use above config
- Create a Typescript or a JavaScript file (say `index.ts`)
- For its content, write

```ts
const  MONDAY = "one";
```

(Notice two spaces between `const` and the variable `MONDAY`)

- Hit `:w`
- Notice that file is being saved two times, first time as is and then followed by formatted content. 

**Expected behaviour**

File to be saved only once, after the content of the file is formatted. 

Converting to `autocmd BufWritePre *.ts,*.js,*.tsx,*.jsx,*.json Format` also doesn't work as file is saved first and formatter formats the content afterwards resulting in buffer in modified state.

**Comment by lukas-reineke** [comment]
This is by design. The plugin is asynchronous.
To prevent blocking the editor while waiting for the formatter to run before saving, we save first, run the formatter, then save again (only if there were no changes in between).

If you absolutely need to only save once, you can run the formatter withh just `:Format` (without save), and then save on the `FormatterPost` autocommand.

**Comment by zlksnk** [comment]
Okay thanks! Posting this for further reading: https://github.com/mhartington/formatter.nvim/issues/7
