### ISSUE TITLE
Avoid populating `:changes` list with first line of file on each save?

### ISSUE THREAD

**Issue by benfrain** [mhartington/formatter.nvim#73]
At present, I have formatter set to run Prettier when I save a file. However, this seems to make all the `:changes` be populated by the entire file (so `:changes` in any file is just a list of the first line in the file).

Is there any way of avoiding this outcome? I'm loathe to give up Formatter doing its  thing on save but I'd also like to have `:changes` functionality.

This  is the command I am running:

```vim.api.nvim_exec(
  [[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.js,*.ts,*.css,*.scss,*.md,*.html,*.lua : FormatWrite
augroup END
]],
  true
)
```

**Comment by lukas-reineke** [comment]
This is a pretty complex problem, so I don't think this plugin will support it. That being said, I actually implemented this for https://github.com/mattn/efm-langserver
It is one of the reasons I personally use efm instead of formatter.nvim.

The way I solved it there is, efm first formats the file with whatever formatter you want (for example prettier), then computes edits using the myers diff algorithm to get from the previous version to the new version with as little changes as possible.
The LSP protocol specifies these [text edits](https://microsoft.github.io/language-server-protocol/specification.html#textEdit), so Neovim supports them as well.

In theory, this plugin could do the same. But it is a lot of work.

**Comment by mhartington** [comment]
This doesn't seem like _that_ big of a deal, so probably not going to do anything here. You _could_ use `undojoin` to merge changes together


```
augroup fmt
  autocmd!
  autocmd BufWritePre * undojoin | FormatWrite
augroup END 
```

But haven't tried this myself.
